name: rn
channels:
- conda-forge
- defaults
dependencies:
    - matplotlib
    - seaborn
    - pandas
    - jupyter
    - tensorflow
    - numpy
    - scikit-learn
    - pip
    - pip:
        - rnutil