name: rn
channels:
- conda-forge
- defaults
- anaconda
dependencies:
    - matplotlib
    - seaborn
    - pandas
    - jupyter
    - jupyterlab
    - cudatoolkit
    - numpy
    - scikit-learn
    - pip
    - pip:
        - rnutil
        - tf-nightly
